CREATE TABLE IF NOT EXISTS user_wallets (
    user_id BIGINT PRIMARY KEY,
    balance DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_wallets_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
