name: Go Main CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  secrets:
    name: Secret Scan (Gitleaks)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  vuln-check:
    name: Govulncheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: false
          
      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: 1.23
           go-package: ./...

  lint:
    name: GolangCI-Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: false

      - name: Run Linters
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

  test:
    name: Test & Build (Go ${{ matrix.go-version }})
    runs-on: ubuntu-latest
    needs: [lint]
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.24']

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Dependencies
        run: go mod download

      - name: Run Unit Tests (with Race Detection)
        # -race matches production concurrency issues
        # -cover adds coverage reporting
        run: go test -v -race -cover ./...

      - name: Verify Build
        # Ensures the code actually compiles into a binary
        run: go build -v ./...